version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
  redis:
    container_name: redis
    image: redis:6.0.5-alpine
    ports:
      - "6379:6379"
